<a href="https://colab.research.google.com/github/akshayreddy11/pyTorch/blob/main/pytorch_fundamentals_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello I'm  excited to learn pytorch")

hello I'm  excited to learn pytorch


In [2]:
!nvidia-smi

Fri Feb  9 16:45:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensore
   ### Creating tensors

In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
#Get tensor back as Python int
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [18]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors
Why random tensors?

the way many random networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


In [28]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7152, 0.4573, 0.4814, 0.3661],
        [0.0858, 0.7810, 0.0976, 0.6948],
        [0.5922, 0.1002, 0.8959, 0.2379]])

In [29]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.1734, 0.8367, 0.6891, 0.0921, 0.3018, 0.6544, 0.6109, 0.1690, 0.1036,
         0.7247],
        [0.3253, 0.8236, 0.0457, 0.5370, 0.5525, 0.7627, 0.0565, 0.6081, 0.8957,
         0.5527],
        [0.3195, 0.1701, 0.7338, 0.6470, 0.9088, 0.0306, 0.0916, 0.5363, 0.2260,
         0.6535],
        [0.7453, 0.7452, 0.5882, 0.4585, 0.7846, 0.5932, 0.0725, 0.8819, 0.6842,
         0.1559],
        [0.3165, 0.0610, 0.2556, 0.3514, 0.8235, 0.3364, 0.3113, 0.3626, 0.7351,
         0.2066],
        [0.4029, 0.2535, 0.9717, 0.4452, 0.0994, 0.1205, 0.5926, 0.2396, 0.4982,
         0.9032],
        [0.3026, 0.8166, 0.2723, 0.8385, 0.3122, 0.7991, 0.7433, 0.9398, 0.6437,
         0.0575],
        [0.8201, 0.8908, 0.4444, 0.9770, 0.5901, 0.2005, 0.5231, 0.7521, 0.8260,
         0.4712],
        [0.1790, 0.5909, 0.5404, 0.9317, 0.9755, 0.9201, 0.5575, 0.8323, 0.6748,
         0.2966],
        [0.0495, 0.0323, 0.2789, 0.6227, 0.0657, 0.4341, 0.4485, 0.5103, 0.1296,
         0.0536]])

In [30]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(123, 123, 3))#height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([123, 123, 3]), 3)

In [32]:
torch.rand(3,4)

tensor([[0.5537, 0.2488, 0.9887, 0.4961],
        [0.5136, 0.7660, 0.6208, 0.4130],
        [0.1071, 0.3464, 0.7317, 0.4182]])

###Zeros and ones

In [35]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensor-like

In [39]:
#Use torch.range()
torch.range(0, 10)

<ipython-input-39-fef3e921b5bb>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
torch.__version__

'2.1.0+cu121'

In [42]:
#Use torch.range()
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [43]:
#Use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
#Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes

In [48]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [54]:
int_32_tensor = torch.tensor([3,6,9], dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)